name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Java code
        run: javac -cp .:lib/* src/**/*.java

      - name: Run JUnit tests
        run: java -cp .:lib/*:src org.junit.runner.JUnitCore your.package.TestClassName
