name: Java CI

on:
  push:
    branches: [ "main" ]   # only run CI when code reaches main
  pull_request:
    branches: [ "main" ]   # run CI when someone opens a PR into main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
